image:
  blob:
    repository: mcr.microsoft.com/k8s/csi/blob-csi
    tag: v0.7.1
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner
    tag: v1.4.0
    pullPolicy: IfNotPresent
  csiAttacher:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-attacher
    tag: v2.2.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
    tag: v1.1.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
    tag: v1.2.0
    pullPolicy: IfNotPresent

serviceAccount:
  create: true

rbac:
  create: true

controller:
  replicas: 2

node:
  metricsPort: 29625
