---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: blob.csi.azure.com
spec:
  attachRequired: false
  podInfoOnMount: true
  {{- if .Values.feature.enableFSGroupPolicy}}
  fsGroupPolicy: File
  {{- end}}
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
